sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t8iB77zTUB1uJf7UJzS
    access-key-secret: ZFB5oGeH3BbvfQd8sxHzEPcxfg5OaO
    bucket-name: sky-takeout-0420
